### ISSUE TITLE
Publicing `eagle-js` code

### ISSUE THREAD

**Issue by hewcaw** [petamorikei/DemolisherTracker#1]
Hi bro, sorry for bothering! The story is, I just found a couple of bugs inside https://www.npmjs.com/package/@petamorikei/eagle-js that makes it unusable, so it would be nice if you could push the code on GitHub for us fellows to fix them, thank you a lot!

**Comment by petamorikei** [comment]
Hi! Thank you for reporting. I've made the repo public now.
I would be happy if you could open a new issue describing the problem in this repository.
https://github.com/petamorikei/eagle-js
